export interface Location {
  slug: string
  displayName: string
  state: string
}

export const locations: Location[] = [
  { slug: 'sibu', displayName: 'Sibu', state: 'Sarawak' },
  { slug: 'dungun', displayName: 'Dungun', state: 'Terengganu' },
  { slug: 'kota-laksamana', displayName: 'Kota Laksamana', state: 'Melaka' },
  { slug: 'seberang-jaya', displayName: 'Seberang Jaya', state: 'Pulau Pinang' },
  { slug: 'arau', displayName: 'Arau', state: 'Perlis' },
  { slug: 'mont-kiara', displayName: 'Mont Kiara', state: 'Kuala Lumpur' },
  { slug: 'subang-jaya', displayName: 'Subang Jaya', state: 'Selangor' },
  { slug: 'kuala-krai', displayName: 'Kuala Krai', state: 'Kelantan' },
  { slug: 'gua-musang', displayName: 'Gua Musang', state: 'Kelantan' },
  { slug: 'damansara-heights', displayName: 'Damansara Heights', state: 'Kuala Lumpur' },
  { slug: 'segambut', displayName: 'Segambut', state: 'Kuala Lumpur' },
  { slug: 'gombak', displayName: 'Gombak', state: 'Selangor' },
  { slug: 'kuching', displayName: 'Kuching', state: 'Sarawak' },
  { slug: 'ipoh', displayName: 'Ipoh', state: 'Perak' },
  { slug: 'rembau', displayName: 'Rembau', state: 'Negeri Sembilan' },
  { slug: 'shah-alam', displayName: 'Shah Alam', state: 'Selangor' },
  { slug: 'sarawak', displayName: 'Sarawak', state: 'Sarawak' },
  { slug: 'bangsar', displayName: 'Bangsar', state: 'Kuala Lumpur' },
  { slug: 'padang-besar', displayName: 'Padang Besar', state: 'Perlis' },
  { slug: 'bukit-cina', displayName: 'Bukit Cina', state: 'Melaka' },
  { slug: 'raub', displayName: 'Raub', state: 'Pahang' },
  { slug: 'setapak', displayName: 'Setapak', state: 'Kuala Lumpur' },
  { slug: 'nibong-tebal', displayName: 'Nibong Tebal', state: 'Pulau Pinang' },
  { slug: 'puchong', displayName: 'Puchong', state: 'Selangor' },
  { slug: 'bandar-puchong', displayName: 'Bandar Puchong', state: 'Selangor' },
  { slug: 'kuala-lumpur', displayName: 'Kuala Lumpur', state: 'Kuala Lumpur' },
  { slug: 'kota-setar', displayName: 'Kota Setar', state: 'Kedah' },
  { slug: 'perak', displayName: 'Perak', state: 'Perak' },
  { slug: 'kuala-pilah', displayName: 'Kuala Pilah', state: 'Negeri Sembilan' },
  { slug: 'mid-valley', displayName: 'Mid Valley', state: 'Kuala Lumpur' },
  { slug: 'sunway-velocity', displayName: 'Sunway Velocity', state: 'Kuala Lumpur' },
  { slug: 'jempol', displayName: 'Jempol', state: 'Negeri Sembilan' },
  { slug: 'kelantan', displayName: 'Kelantan', state: 'Kelantan' },
  { slug: 'sri-petaling', displayName: 'Sri Petaling', state: 'Kuala Lumpur' },
  { slug: 'ampang', displayName: 'Ampang', state: 'Selangor' },
  { slug: 'marang', displayName: 'Marang', state: 'Terengganu' },
  { slug: 'hulu-langat', displayName: 'Hulu Langat', state: 'Selangor' },
  { slug: 'george-town', displayName: 'George Town', state: 'Pulau Pinang' },
  { slug: 'kinta', displayName: 'Kinta', state: 'Perak' },
  { slug: 'perlis', displayName: 'Perlis', state: 'Perlis' },
  { slug: 'muar', displayName: 'Muar', state: 'Johor' },
  { slug: 'pulau-pinang', displayName: 'Pulau Pinang', state: 'Pulau Pinang' },
  { slug: 'skudai', displayName: 'Skudai', state: 'Johor' },
  { slug: 'ayer-keroh', displayName: 'Ayer Keroh', state: 'Melaka' },
  { slug: 'sungai-petani', displayName: 'Sungai Petani', state: 'Kedah' },
  { slug: 'temerloh', displayName: 'Temerloh', state: 'Pahang' },
  { slug: 'kemaman', displayName: 'Kemaman', state: 'Terengganu' },
  { slug: 'sentul', displayName: 'Sentul', state: 'Kuala Lumpur' },
  { slug: 'cheras', displayName: 'Cheras', state: 'Kuala Lumpur' },
  { slug: 'taiping', displayName: 'Taiping', state: 'Perak' },
  { slug: 'klang-valley', displayName: 'Klang Valley', state: 'Selangor' },
  { slug: 'bandar-utama', displayName: 'Bandar Utama', state: 'Selangor' },
  { slug: 'melaka', displayName: 'Melaka', state: 'Melaka' },
  { slug: 'selangor', displayName: 'Selangor', state: 'Selangor' },
  { slug: 'cameron-highlands', displayName: 'Cameron Highlands', state: 'Pahang' },
  { slug: 'jerantut', displayName: 'Jerantut', state: 'Pahang' },
  { slug: 'sungai-buloh', displayName: 'Sungai Buloh', state: 'Selangor' },
  { slug: 'seri-manjung', displayName: 'Seri Manjung', state: 'Perak' },
  { slug: 'kuala-perlis', displayName: 'Kuala Perlis', state: 'Perlis' },
  { slug: 'kuchai-lama', displayName: 'Kuchai Lama', state: 'Kuala Lumpur' },
  { slug: 'serdang', displayName: 'Serdang', state: 'Selangor' },
  { slug: 'segamat', displayName: 'Segamat', state: 'Johor' },
  { slug: 'terengganu', displayName: 'Terengganu', state: 'Terengganu' },
  { slug: 'machang', displayName: 'Machang', state: 'Kelantan' },
  { slug: 'miri', displayName: 'Miri', state: 'Sarawak' },
  { slug: 'manjung', displayName: 'Manjung', state: 'Perak' },
  { slug: 'sepang', displayName: 'Sepang', state: 'Selangor' },
  { slug: 'batu-pahat', displayName: 'Batu Pahat', state: 'Johor' },
  { slug: 'damansara', displayName: 'Damansara', state: 'Selangor' },
  { slug: 'butterworth', displayName: 'Butterworth', state: 'Pulau Pinang' },
  { slug: 'kajang', displayName: 'Kajang', state: 'Selangor' },
  { slug: 'kulim', displayName: 'Kulim', state: 'Kedah' },
  { slug: 'seremban', displayName: 'Seremban', state: 'Negeri Sembilan' },
  { slug: 'rawang', displayName: 'Rawang', state: 'Selangor' },
  { slug: 'johor', displayName: 'Johor', state: 'Johor' },
  { slug: 'kulai', displayName: 'Kulai', state: 'Johor' },
  { slug: 'desa-parkcity', displayName: 'Desa ParkCity', state: 'Kuala Lumpur' },
  { slug: 'bangsar-south', displayName: 'Bangsar South', state: 'Kuala Lumpur' },
  { slug: 'pahang', displayName: 'Pahang', state: 'Pahang' },
  { slug: 'putrajaya', displayName: 'Putrajaya', state: 'Putrajaya' },
  { slug: 'besut', displayName: 'Besut', state: 'Terengganu' },
  { slug: 'bintulu', displayName: 'Bintulu', state: 'Sarawak' },
  { slug: 'kangar', displayName: 'Kangar', state: 'Perlis' },
  { slug: 'jitra', displayName: 'Jitra', state: 'Kedah' },
  { slug: 'kampar', displayName: 'Kampar', state: 'Perak' },
  { slug: 'alor-gajah', displayName: 'Alor Gajah', state: 'Melaka' },
  { slug: 'bukit-bintang', displayName: 'Bukit Bintang', state: 'Kuala Lumpur' },
  { slug: 'pekan', displayName: 'Pekan', state: 'Pahang' },
  { slug: 'pantai-dalam', displayName: 'Pantai Dalam', state: 'Kuala Lumpur' },
  { slug: 'taman-desa', displayName: 'Taman Desa', state: 'Kuala Lumpur' },
  { slug: 'negeri-sembilan', displayName: 'Negeri Sembilan', state: 'Negeri Sembilan' },
  { slug: 'petaling-jaya', displayName: 'Petaling Jaya', state: 'Selangor' },
  { slug: 'seksyen-7', displayName: 'Seksyen 7', state: 'Selangor' },
  { slug: 'sabah', displayName: 'Sabah', state: 'Sabah' },
  { slug: 'bandar-baru-bangi', displayName: 'Bandar Baru Bangi', state: 'Selangor' },
  { slug: 'kuantan', displayName: 'Kuantan', state: 'Pahang' },
  { slug: 'bukit-mertajam', displayName: 'Bukit Mertajam', state: 'Pulau Pinang' },
  { slug: 'setiawangsa', displayName: 'Setiawangsa', state: 'Kuala Lumpur' },
  { slug: 'sungai-dua', displayName: 'Sungai Dua', state: 'Pulau Pinang' },
  { slug: 'jasin', displayName: 'Jasin', state: 'Melaka' },
  { slug: 'tanah-merah', displayName: 'Tanah Merah', state: 'Kelantan' },
  { slug: 'kota-kinabalu', displayName: 'Kota Kinabalu', state: 'Sabah' },
  { slug: 'penang', displayName: 'Penang', state: 'Pulau Pinang' },
  { slug: 'alor-setar', displayName: 'Alor Setar', state: 'Kedah' },
  { slug: 'sandakan', displayName: 'Sandakan', state: 'Sabah' },
  { slug: 'kota-bharu', displayName: 'Kota Bharu', state: 'Kelantan' },
  { slug: 'bahau', displayName: 'Bahau', state: 'Negeri Sembilan' },
  { slug: 'bangi', displayName: 'Bangi', state: 'Selangor' },
  { slug: 'kedah', displayName: 'Kedah', state: 'Kedah' },
  { slug: 'taman-tun-dr.-ismail-(ttdi)', displayName: 'TTDI', state: 'Kuala Lumpur' },
  { slug: 'klang', displayName: 'Klang', state: 'Selangor' },
  { slug: 'johor-bahru', displayName: 'Johor Bahru', state: 'Johor' },
  { slug: 'old-klang-road', displayName: 'Old Klang Road', state: 'Kuala Lumpur' },
  { slug: 'langkawi', displayName: 'Langkawi', state: 'Kedah' },
  { slug: 'sri-hartamas', displayName: 'Sri Hartamas', state: 'Kuala Lumpur' },
  { slug: 'tawau', displayName: 'Tawau', state: 'Sabah' },
  { slug: 'kepong', displayName: 'Kepong', state: 'Kuala Lumpur' },
  { slug: 'port-dickson', displayName: 'Port Dickson', state: 'Negeri Sembilan' },
  { slug: 'kuala-terengganu', displayName: 'Kuala Terengganu', state: 'Terengganu' },
  { slug: 'balik-pulau', displayName: 'Balik Pulau', state: 'Pulau Pinang' },
  { slug: 'taman-melawati', displayName: 'Taman Melawati', state: 'Selangor' },
]

export const nearbyLocations: Record<string, string[]> = {
  'kuala-lumpur': ['petaling-jaya', 'shah-alam', 'cheras', 'ampang', 'bangsar'],
  'petaling-jaya': ['kuala-lumpur', 'shah-alam', 'subang-jaya', 'damansara', 'puchong'],
  'johor-bahru': ['skudai', 'kulai', 'muar', 'batu-pahat', 'segamat'],
  'george-town': ['butterworth', 'bukit-mertajam', 'balik-pulau', 'nibong-tebal', 'sungai-dua'],
  'ipoh': ['kampar', 'taiping', 'seri-manjung', 'manjung', 'kinta'],
  'kuching': ['sibu', 'bintulu', 'miri', 'sarawak'],
  'kota-kinabalu': ['sandakan', 'tawau', 'sabah'],
  'melaka': ['ayer-keroh', 'alor-gajah', 'jasin', 'kota-laksamana', 'bukit-cina'],
  'seremban': ['port-dickson', 'rembau', 'bahau', 'kuala-pilah', 'jempol'],
  'kota-bharu': ['machang', 'tanah-merah', 'gua-musang', 'kuala-krai', 'besut'],
  'kuala-terengganu': ['dungun', 'marang', 'kemaman', 'terengganu'],
  'alor-setar': ['jitra', 'kangar', 'kulim', 'sungai-petani', 'padang-besar'],
  'shah-alam': ['klang', 'seksyen-7', 'subang-jaya', 'petaling-jaya', 'puchong'],
  'cheras': ['sri-petaling', 'serdang', 'kajang', 'hulu-langat', 'bandar-baru-bangi'],
  'bangsar': ['mid-valley', 'bangsar-south', 'pantai-dalam', 'kuchai-lama', 'taman-desa'],
  'kepong': ['segambut', 'setapak', 'sentul', 'rawang', 'gombak'],
  'mont-kiara': ['desa-parkcity', 'sri-hartamas', 'damansara-heights', 'taman-tun-dr.-ismail-(ttdi)'],
}

export function getNearbyLocations(slug: string): Location[] {
  const nearbySlugs = nearbyLocations[slug] ?? []
  return nearbySlugs
    .map(s => locations.find(l => l.slug === s))
    .filter((l): l is Location => l !== undefined)
    .slice(0, 5)
}

export const footerLocations: Location[] = [
  { slug: 'kuala-lumpur', displayName: 'Kuala Lumpur', state: 'Kuala Lumpur' },
  { slug: 'petaling-jaya', displayName: 'Petaling Jaya', state: 'Selangor' },
  { slug: 'shah-alam', displayName: 'Shah Alam', state: 'Selangor' },
  { slug: 'johor-bahru', displayName: 'Johor Bahru', state: 'Johor' },
  { slug: 'george-town', displayName: 'George Town', state: 'Pulau Pinang' },
  { slug: 'ipoh', displayName: 'Ipoh', state: 'Perak' },
]
